FROM node:20-alpine AS build

WORKDIR /app

# Install dependencies and build
COPY frontend/react-app/package.json ./
COPY frontend/react-app/package-lock.json ./
RUN npm ci --silent

COPY frontend/react-app/ ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/react-app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
